# Generated by Django 5.1.6 on 2025-02-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_deta',
            new_name='created_date',
        ),
    ]
